Export commonly used function as top-level object
taskcluster/taskcluster-lib-docs pull request #20
Opened 2017-01-09 15:52 UTC by jonasfj

2017-01-09 16:29 UTC, jonasfj commented
@imbstack also have a look at:
https://bugzilla.mozilla.org/show_bug.cgi?id=1329679
Maybe it's a good first bug?

2017-01-10 15:49 UTC, imbstack approved these changes

2017-01-10 15:50 UTC, imbstack requested changes
Don't bump the version in this change. Do it after it is merged with `npm version minor` and then push to master. Otherwise r+!

2017-01-10 15:52 UTC, imbstack approved these changes

2017-01-10 15:52 UTC, merged